// Les 32 équipes de la LNH, telles que les renvoie ESPN (…/hockey/nhl/teams,
// saison 2026-27). Intégrées à l'app parce que cette adresse d'ESPN est
// illisible depuis une application : son pare-feu refuse le relais Rust et elle
// n'autorise pas la lecture depuis WebView2. Les identifiants sont ceux d'ESPN,
// les mêmes que dans les résultats des matchs.
const LOGO = (abbr) => `https://a.espncdn.com/i/teamlogos/nhl/500/${abbr.toLowerCase()}.png`;

export const NHL_TEAMS = [
  { id: "25", abbr: "ANA", name: "Anaheim Ducks", short: "Ducks", color: '#fc4c02' },
  { id: "1", abbr: "BOS", name: "Boston Bruins", short: "Bruins", color: '#231f20' },
  { id: "2", abbr: "BUF", name: "Buffalo Sabres", short: "Sabres", color: '#00468b' },
  { id: "3", abbr: "CGY", name: "Calgary Flames", short: "Flames", color: '#dd1a32' },
  { id: "7", abbr: "CAR", name: "Carolina Hurricanes", short: "Hurricanes", color: '#e30426' },
  { id: "4", abbr: "CHI", name: "Chicago Blackhawks", short: "Blackhawks", color: '#e31937' },
  { id: "17", abbr: "COL", name: "Colorado Avalanche", short: "Avalanche", color: '#860038' },
  { id: "29", abbr: "CBJ", name: "Columbus Blue Jackets", short: "Blue Jackets", color: '#002d62' },
  { id: "9", abbr: "DAL", name: "Dallas Stars", short: "Stars", color: '#20864c' },
  { id: "5", abbr: "DET", name: "Detroit Red Wings", short: "Red Wings", color: '#e30526' },
  { id: "6", abbr: "EDM", name: "Edmonton Oilers", short: "Oilers", color: '#00205b' },
  { id: "26", abbr: "FLA", name: "Florida Panthers", short: "Panthers", color: '#e51937' },
  { id: "8", abbr: "LA", name: "Los Angeles Kings", short: "Kings", color: '#121212' },
  { id: "30", abbr: "MIN", name: "Minnesota Wild", short: "Wild", color: '#124734' },
  { id: "10", abbr: "MTL", name: "Montreal Canadiens", short: "Canadiens", color: '#c41230' },
  { id: "27", abbr: "NSH", name: "Nashville Predators", short: "Predators", color: '#fdba31' },
  { id: "11", abbr: "NJ", name: "New Jersey Devils", short: "Devils", color: '#e30b2b' },
  { id: "12", abbr: "NYI", name: "New York Islanders", short: "Islanders", color: '#00529b' },
  { id: "13", abbr: "NYR", name: "New York Rangers", short: "Rangers", color: '#0056ae' },
  { id: "14", abbr: "OTT", name: "Ottawa Senators", short: "Senators", color: '#dd1a32' },
  { id: "15", abbr: "PHI", name: "Philadelphia Flyers", short: "Flyers", color: '#fe5823' },
  { id: "16", abbr: "PIT", name: "Pittsburgh Penguins", short: "Penguins", color: '#000000' },
  { id: "18", abbr: "SJ", name: "San Jose Sharks", short: "Sharks", color: '#00788a' },
  { id: "124292", abbr: "SEA", name: "Seattle Kraken", short: "Kraken", color: '#000d33' },
  { id: "19", abbr: "STL", name: "St. Louis Blues", short: "Blues", color: '#0070b9' },
  { id: "20", abbr: "TB", name: "Tampa Bay Lightning", short: "Lightning", color: '#003e7e' },
  { id: "21", abbr: "TOR", name: "Toronto Maple Leafs", short: "Maple Leafs", color: '#003e7e' },
  { id: "129764", abbr: "UTAH", name: "Utah Mammoth", short: "Mammoth", color: '#000000' },
  { id: "22", abbr: "VAN", name: "Vancouver Canucks", short: "Canucks", color: '#003e7e' },
  { id: "37", abbr: "VGK", name: "Vegas Golden Knights", short: "Golden Knights", color: '#344043' },
  { id: "23", abbr: "WSH", name: "Washington Capitals", short: "Capitals", color: '#d71830' },
  { id: "28", abbr: "WPG", name: "Winnipeg Jets", short: "Jets", color: '#002d62' },
].map((t) => ({ ...t, logo: LOGO(t.abbr) }));
